### ISSUE TITLE
Cron ignores setting timezone after it is added 

### ISSUE THREAD

**Issue by zdila** [mongoose-os-libs/cron#1]
1. leave `sys.tz_spec` unset in `mos.yml`

2. run
    ```
    mgos_cron_add("*0 0 0 * * *", daily_cb, NULL);
    mgos_sys_config_set_sys_tz_spec("CET-1CEST,M3.5.0,M10.5.0/3");
    mgos_sys_config_save(&mgos_sys_config, false, NULL)
    ```
3. cron still executes at 00:00 UTC unless rebooted

**Comment by rojer** [comment]
i think that's because timezone is [only applied on boot](https://github.com/mongoose-os-libs/core/blob/c7359ef09e0f75bd693d88672ba9665b84d0e46a/src/mgos_core.c#L100-L108), so entire system is not using it until reboot.
config_set only sets the variable, you need to run setenv and tzset as well.

**Comment by zdila** [comment]
oh, i forgot, we also call `tzset`. I will try also `setenv`.

**Comment by rojer** [comment]
ok, so this is working as designed, more or less. in general, we say that you need to reboot for config changes to take effect. if this is to ever change, it will be a separate issue.
