### ISSUE TITLE
ccronexpr.c:487:16: error: Memory leak: str [memleak]

### ISSUE THREAD

**Issue by Harvie** [mongoose-os-libs/cron#2]
```
$ cppcheck cron
Checking cron/src/ccronexpr.c ...
cron/src/ccronexpr.c:487:16: error: Memory leak: str [memleak]
  if (res < 0) return NULL;
               ^
Checking cron/src/ccronexpr.c: ANDROID...
Checking cron/src/ccronexpr.c: CRON_COMPILE_AS_CXX...
Checking cron/src/ccronexpr.c: _WIN32...
1/11 files checked 33% done
Checking cron/src/mgos_cron.c ...
Checking cron/src/mgos_cron.c: ANDROID...
Checking cron/src/mgos_cron.c: CRON_COMPILE_AS_CXX...
Checking cron/src/mgos_cron.c: MGOS_FREE_BUILD...
Checking cron/src/mgos_cron.c: _REENT...
2/11 files checked 60% done
Checking cron/src/sunriset.c ...
3/11 files checked 76% done
Checking cron/test/cron_test.c ...
4/11 files checked 94% done
Checking cron/test/cs_dbg.c ...
5/11 files checked 94% done
Checking cron/test/mgos_hal.c ...
6/11 files checked 94% done
Checking cron/test/mgos_location.c ...
7/11 files checked 95% done
Checking cron/test/mgos_sys_config.c ...
8/11 files checked 95% done
Checking cron/test/mgos_timers.c ...
9/11 files checked 99% done
Checking cron/test/mgos_utils.c ...
10/11 files checked 99% done
Checking cron/test/sunriset.c ...
11/11 files checked 100% done

```

**Comment by rojer** [comment]
fixed, thanks!

**Comment by Harvie** [comment]
Actualy i've found a lots of warnings using cppcheck, but i handpicked just few that seemed most likely to be actual problems and easy to fix... Because the cppcheck is rather limited, i would love to be able to use the clang analyzer, which is bit more advanced. But to work properly it does need to analyze whole project to be able to cross-reference everything properly, which means it has to work as wrapper around the build system. Unfortunately in mongoose this would mean to include clang analyzer package directly into the docker image doing the build... https://github.com/mongoose-os/mos/issues/39

I don't really want to use clang analyzer to nitpick on mongoose os code quality, but it would be supper handy to get quick overview of my mongoose based application code.

**Comment by rojer** [comment]
i don't see it as nitpicking at all, these are real bugs and should be fixed.

**Comment by rojer** [comment]
i repled on the issue - yes, i think we should do it, and if you can, please go ahead.
