### ISSUE TITLE
Cron Causes Crash from DST change

### ISSUE THREAD

**Issue by jconstam** [mongoose-os-libs/cron#4]
I am setting a cron job to execute approximately once per day using the following expression:
`"@random:{\"from\":\"0 0 0 * * *\", \"to\":\"59 59 23 * * *\", \"number\":1}"`

This lead to a crash caused by the [assert on line 343 of `mgos_cron.c`](https://github.com/mongoose-os-libs/cron/blob/7ecbf83654997172e0ad5611be2e879e44724919/src/mgos_cron.c#L343).

For me, the issue only occurs between 16:00 MST and 23:59 MST on March 13, 2021.  Note that this is on the day before the transition from MST to MDT.

I did some digging and found that the variables used in the calculation in `s_cron_next` are as follows:
|Variable|Time Value|Date GMT|Date MST|
|-|-|-|-|
|`from`|1615618800|Saturday, March 13, 2021 7:00:00 AM GMT|Saturday, March 13, 2021 12:00:00 AM GMT-07:00|
|`to`|1615705199|Sunday, March 14, 2021 6:59:59 AM GMT|Saturday, March 13, 2021 11:59:59 PM GMT-07:00|
|`date`|1615681800|Sunday, March 14, 2021 12:30:00 AM GMT|Saturday, March 13, 2021 5:30:00 PM GMT-07:00|

Since `from < to`, the code inside the [`if` statement on line 318](https://github.com/mongoose-os-libs/cron/blob/7ecbf83654997172e0ad5611be2e879e44724919/src/mgos_cron.c#L318) is not executed.  When `s_next_random` is [called on line 342](https://github.com/mongoose-os-libs/cron/blob/7ecbf83654997172e0ad5611be2e879e44724919/src/mgos_cron.c#L342), it is easily possible for [`cur` on line 186](https://github.com/mongoose-os-libs/cron/blob/7ecbf83654997172e0ad5611be2e879e44724919/src/mgos_cron.c#L186) to be less than `now` (aka `date` in `s_cron_next`).  This leads to the `assert` failing.

When executed on a different day, `date` is always less than `from` and the math works out.  I am not sure why this only happens on the day before the change to daylight saving time but I think it has to do with March 14, 2021 only having 23 hours.  Since `date` seems to be the "incorrect" variable, I would suspect the issue comes from the value of `ce->planned_time` set [on line 678 in `mgos_cron_add`](https://github.com/mongoose-os-libs/cron/blob/7ecbf83654997172e0ad5611be2e879e44724919/src/mgos_cron.c#L678).

**Comment by jconstam** [comment]
On further investigation, it actually seems like the problem is the calculation for `from` and `to` using `cron_next`.  In both the good and bad cases, `date` will be equal to the current time.  However, in the bad case, `from` and `to` are on the same day as `date` whereas in the good case, `from` and `to` are on the day *after* `date`.

**Comment by rojer** [comment]
ah, don't we all love DST? a wonderful thing.

thank you for the detailed analysis of the problem, if you could also submit a PR to fix it, that would be wonderfult

**Comment by olii** [comment]
I think I suffer from a similar bug in regards to DST. Here is my env:
```yaml
config_schema:
  # CET-CEST.
  - ["sys.tz_spec", "CET-1CEST,M3.5.0,M10.5.0/3"]
```

Cron is registered to run at midnight:
```cpp
mgos_cron_add("0 0 0 * * *", midnight_task, NULL);
```

When the device boots and gets the time using NTP then the time of new invocation is recomputed and causes an infinite loop. Watchdog then restarts the device.

**The issue started 24 hours before the DTS change.**

I think I located the problem to be [this loop](https://github.com/mongoose-os-libs/cron/blob/master/src/mgos_cron.c#L422-L434). This is only my guess. I don't know how to run tests for this library.

Here is a part of the log after the device boots:
```
[Mar 26 20:47:56.040] mgos_cron.c:727         Rescheduling cron job 0x3fff0d14 after time change
[Mar 26 20:47:56.047] mgos_cron.c:229         Next invocation: 1648249200 [2022/03/25 23:00:00 UTC]
[Mar 26 20:47:56.053] mgos_cron.c:404         (after -74877 seconds)
[Mar 26 20:47:56.059] mgos_cron.c:229         Next invocation: 1648249200 [2022/03/25 23:00:00 UTC]
[Mar 26 20:47:56.065] mgos_cron.c:404         (after -74877 seconds)
[Mar 26 20:47:56.072] mgos_cron.c:229         Next invocation: 1648249200 [2022/03/25 23:00:00 UTC]
[Mar 26 20:47:56.077] mgos_cron.c:404         (after -74877 seconds)
[Mar 26 20:47:56.084] mgos_cron.c:229         Next invocation: 1648249200 [2022/03/25 23:00:00 UTC]
[Mar 26 20:47:56.090] mgos_cron.c:404         (after -74877 seconds)
[Mar 26 20:47:56.094] mgos_cron.c:229         Next invocation: 1648249200 [2022/03/25 23:00:00 UTC]
... Lines truncated ...
```

As you can see in the log the date of the next invocation is computed to be ... yesterday ... 

Note: `[Mar 26 20:47:56.040]` is in my local timezone - `CET`.

**Comment by svenehlers** [comment]
We had the same issue 24h and less before the DST at 27.3.2022 with some of our daily executed cron jobs. The jobs are executed at a specific clock time each day. A lot of our customers got inoperable devices at that weekend and needed support to get them operable again.

When a cron job in the timespan of 24h before DST got fired the calculation of time until this cron job is fired again resulted in a negative amount of time. This calculation is repeated infinitly until Mongoose OS crashes.

Our timezone is defined by "CET-1CEST,M3.5.0/2,M10.5.0/3" and the logs looked similar as @olii described.

**Comment by kzyapkov** [comment]
I am not sure about the "random" timespec crash originally reported, but we definitely saw infinite loops as described by @olii and confirmed by @svenehlers .

This sems to have been [reported](https://github.com/staticlibs/ccronexpr/issues/15) and [fixed](https://github.com/staticlibs/ccronexpr/pull/20/commits/12a3a4aa6b5945f506416945d647b3e9a3a16769)

Hence, https://github.com/mongoose-os-libs/cron/pull/7

**Comment by rojer** [comment]
thanks @kzyapkov , merged the PR.
i'll close this issue, please reopen if the issue hasn't been fixed by the latest update.
